import { ExtractedData } from '@/types';

export function generateMarkdown(data: ExtractedData): string {
  return `# Problem Validation Report
Generated by Problem Hacker

## Problem Statement
${data.problem_statement || 'Not yet defined'}

## Target Customer
${data.target_customer || 'Not yet defined'}

## Business Metrics

### Urgency Level
${data.biz_metrics.urgency_level || 'Not assessed'}

### Core Instinct
${data.biz_metrics.core_instinct || 'Not identified'}

### Frequency
${data.biz_metrics.frequency || 'Not determined'}

### Current Alternative
${data.biz_metrics.current_alternative || 'Not explored'}

### Sunk Cost Analysis
${data.biz_metrics.sunk_cost_calc || 'Not calculated'}

## Solution Direction
${data.solution_direction || 'Not yet defined'}

---
*Validated on ${new Date().toISOString()}*
`;
}
